UniversityManagement/Models/ClassRoom.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagement.Models
{
    public class ClassRoom
    {
        public int RoomId { get; set; }
        public string RoomNumber { get; set; }
    }
}

UniversityManagement/Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagement.Manager;
using UniversityManagement.Models;

namespace UniversityManagement.Controllers
{
    public class ClassRoomController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        CourseManager aCourseManager = new CourseManager();
        RoomManager aRoomManager = new RoomManager();
        //
        // GET: /ClassRoom/
        public ActionResult Index()
        {
           
            return View();


        }

        public ActionResult UnAllocateClassRoom()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnAllocateClassRoom(string unallocate)
        {
            ViewBag.Message = aCourseManager.UnallocateAllRoom();
            return View();
        }

        public ActionResult ViewClassRoomAllocation()
        {
            
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
            return View();
        }

        public JsonResult GetCourseScheduleByDepartmentId(int departmentId)
        {
            List<ViewCourseSchedule> aCourseSchedules = aCourseManager.GetAllCourseSchedule();
            var courseScheduleList = aCourseSchedules.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(courseScheduleList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AllocateClassRoom()
        {
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
            ViewBag.AllClassRoom = aDepartmentManager.GetAllClassRoom();
            return View();
        }
        [HttpPost]
        public ActionResult AllocateClassRoom(ClassRoomAllocation aClassRoom)
        {
            ViewBag.Message = aRoomManager.Save(aClassRoom);
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
            ViewBag.AllClassRoom = aDepartmentManager.GetAllClassRoom();
            return View();
        }

        public JsonResult GettAllCourseByDepartmentId(int departmentId)
        {
            var courses = aCourseManager.GetAllCourses();

            var courseList = courses.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);


        }

    }
}

UniversityManagement/Views/ClassRoom/AllocateClassRoom.cshtml
@using UniversityManagement.Models
@{
    ViewBag.Title = "Index";
    List<Department> departmentList = ViewBag.AllDepartment;
    List<ClassRoom> roomList = ViewBag.AllClassRoom;

}


<head>
    <style>
        label.error {
            color: red;
            font-weight: bold;
        }
    </style>



</head>
<fieldset style="width:50%">
    <legend>Allocate Classrooms</legend>
    <form method="post" id="AllocateClassRoom" name="AllocateClassRoom">
        @if (ViewBag.Message != null)
            {
                <p style="color: red">@ViewBag.Message</p>
            }

        <table>
            
            <tr>


                <td><label for="DepartmentIdsssss" />Department Name</td>
                <td>

                    <select id="DepartmentIdsssss" name="DepartmentId">
                        <option value="default">...Select...</option>
                        @foreach (var department in departmentList)
                        {
                            <option value="@department.DepartmentId">@department.DepartmentName</option>
                        }


                    </select>

                </td>




            </tr>
            <tr>


                <td><label for="CourseId" />Course Name</td>
                <td>

                    <select id="CourseId" name="CourseId">
                        <option value="default">...Select...</option>
                      


                    </select>

                </td>
            </tr>
            <tr>


                <td><label for="RoomID" />Room No</td>
                <td>

                    <select id="RoomId" name="RoomId">
                        <option value="default">...Select...</option>
                        @foreach (var room in roomList)
            {
                <option value="@room.RoomId">@room.RoomNumber</option>
            }


                    </select>

                </td>
            </tr>
            <tr>


                <td><label for="DayId" />Day</td>
                <td>

                    <select id="DayId" name="Day">
                        <option value="default">...Select...</option>
                        <option value="Sat">Saturday</option>
                        <option value="Sun">Sunday</option>
                        <option value="Mon">Monday</option>
                        <option value="Tue">Tuesday</option>
                        <option value="Wed">Wednesday</option>
                        <option value="Thu">Thursday</option>
                        <option value="Fri">Friday</option>


                    </select>

                </td>
            </tr>
            <tr>
                <td><label for="Form" />Form</td>
                <td><input name="Fromtime" /></td>
                
            </tr>
            <tr>
                <td><label for="To" />To</td>
                <td>
                    <input name="Totime" />
                 </td>
               
            </tr>

            
           
            
            
          
           
            <tr>
                <td></td>
                <td><input type="submit" name="hh" value="Allocate" style="float:right"></td>
            </tr>

        </table>
       
       
        
    </form>
    @section scripts
    {
        <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
        <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/redmond/jquery-ui.css" />
        <link href="~/Scripts/jquery.ptTimeSelect.css" rel="stylesheet" />
        <script src="~/Scripts/jquery.ptTimeSelect.js"></script>

        <script type="text/javascript"> $(document).ready(function() {
    $('input[name="Totime"]').ptTimeSelect();
    $('input[name="Fromtime"]').ptTimeSelect();
    $.validator.addMethod("valueNotEquals", function(value, element, arg) {
        return arg != value;
    }, "Please Select One.");

    $("#AllocateClassRoom").validate({
        rules: {
            DepartmentId: {
                valueNotEquals: "default"
            },
            CourseId: {
                valueNotEquals: "default"

            },
            RoomId: {
                valueNotEquals: "default"
            },
            Day: {
                valueNotEquals: "default"
            },
            Fromtime :{
                required: true
            },
            Totime: {
                required: true
            }
        },
        messages: {
        }
    });
    ///////////Load CourseCode by Department ID
    $("#DepartmentIdsssss").change(function() {
        $("#CourseId").empty();

        var departmentId = $("#DepartmentIdsssss").val();
        var json = { departmentId: departmentId };

        $.ajax({
            type: "POST",
            url: '@Url.Action("GettAllCourseByDepartmentId", "ClassRoom")',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(json),
            success: function(data) {

                $.each(data, function(key, value) {
                    //alert(key);
                    $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                    //$("#CreditToTake").val(value.CreditToTake);


                });


                // ................


                //............
            }
        });

        
    });
    ///////////////


}); </script>
       
        
    }



</fieldset>

UniversityManagement/Views/ClassRoom/UnAllocateClassRoom.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UnAssignCourses</title>
</head>
<body>
    <div>
        <fieldset style="width:50%">
            <legend>Unallocate ClassRoom</legend>
            <form method="post" id="unallocate">
                @if (ViewBag.Message != null)
                {
                    <p>@ViewBag.Message</p>
                }


                <input type="submit" name="unallocate" value="Unallocate ClassRoom" style="text-align: center">

            </form>
        </fieldset>
    </div>
</body>
</html>

UniversityManagement/Views/ClassRoom/ViewClassRoomAllocation.cshtml
@using UniversityManagement.Models
@{
    ViewBag.Title = "Index";
    List<Department> departmentList = ViewBag.AllDepartment;
    List<ClassRoom> roomList = ViewBag.AllClassRoom;

}



<fieldset style="width:50%">
    <legend>View Class Schedule and Room Allocation Information
</legend>
   
    Department: <select id="DepartmentId">
                    <option value="">...Select...</option>
                    @foreach (var department in departmentList)
                    {
                        <option value="@department.DepartmentId">@department.DepartmentName</option>
                    }
                
                
                </select>
    

    <table id="ClassSchedule">
        
        <tbody>
       
            </tbody>

    </table>



    @section scripts
{
        @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
        <script src="~/Scripts/jquery-2.2.0.min.js"></script>
        <script>
            $(document).ready(function () {

                $("#DepartmentId").change(function () {
                    $('#ClassSchedule > tbody > tr').empty();

                    var departmentId = $("#DepartmentId").val();
                    //alert(departmentId);
                    //("#departmentId").empty();
                    var json = { departmentId: departmentId };
                    $.ajax({
                        //
                        type: "POST",
                        url: '@Url.Action("GetCourseScheduleByDepartmentId", "ClassRoom")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {
                            $("#ClassSchedule").append('<tr><th>Course Code</th><th>Course Name</th><th> Schedule Info</th></tr>');
                            

                            $.each(data, function (key, value) {
                                //alert(key);
                                $("#ClassSchedule").append('<tr><td>' + value.CourseCode + '</td>'
                                 + '<td>' + value.CourseName + '</td>'
                                 + '<td>' + value.ScheduleInfo + '</td></tr>'
                                    );
                                //$("#CreditToTake").val(value.CreditToTake);


                            });


                            // ................



                        }
                    });




                });





            });
        </script>
    }



</fieldset>