UniversityManagement/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagement.Models
{
    public class Teacher
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string Address  { get; set; }
        public string Email { get; set; }

        public string ContactNo { get; set; }
        public int DesignationId { get; set; }
        public int DepartmentId { get; set; }
        public int CreditToTake { get; set; }



    }
}

UniversityManagement/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagement.Manager;
using UniversityManagement.Models;

namespace UniversityManagement.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager aTeacherManager = new TeacherManager();
        DepartmentManager aDepartmentManager = new DepartmentManager();
        CourseManager aCourseManager = new CourseManager();
        // GET: Teacher
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UnAssignCourses()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UnAssignCourses( String unassigned)
        {
            ViewBag.Message = aTeacherManager.UnassigneAllCourses();
            return View();
        }

        public ActionResult TestAssignCourse()
        {
            return View();
        }

        [HttpPost]
        public ActionResult TestAssignCourse(AsignCourse asignCourse)
        {
            return View();
        }


        public ActionResult AssignCourse()
        {
            ViewBag.AllTeacher = aTeacherManager.GetAllTeacher();
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
           
            return View();
        }

        [HttpPost]
        public ActionResult AssignCourse(AsignCourse asignCourse)
        {
            ViewBag.AllTeacher = aTeacherManager.GetAllTeacher();
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
            ViewBag.Message = aTeacherManager.AssignCourse(asignCourse);

            return View();
        }

        public JsonResult GetTeachersByDepartmentId(int departmentId)
        {
            var teachers = aTeacherManager.GetAllTeacher();
            var teacherList = teachers.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GettAllCourseByDepartmentId(int departmentId)
        {
            var courses = aCourseManager.GetAllCourses();

            var courseList = courses.Where(a => a.DepartmentId == departmentId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);


        }
        public JsonResult GetAllCouseByCourseId(int courseId)
        {
            var courses = aCourseManager.GetAllCourses();

            var courseList = courses.Where(a => a.CourseId == courseId).ToList();
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }

        public string GettRemainningCreditByTeacherId(int cropName)
        {
            string teacherCredit = aTeacherManager.GettAllRemainningCredit(cropName);

            return teacherCredit;

        }

        public ActionResult SaveTeacher()
        {
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
            ViewBag.AllDesignation = aTeacherManager.GetAllDesignation();


            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher aTeacher)
        {
            ViewBag.AllDepartment = aDepartmentManager.GetAllDepartment();
            ViewBag.AllDesignation = aTeacherManager.GetAllDesignation();
            ViewBag.Message = aTeacherManager.SaveTeacher(aTeacher);


            return View();
        }

       
    }
}

UniversityManagement/Views/Teacher/AssignCourse.cshtml
@using UniversityManagement.Models
@{
    //ViewBag.Title = "Index";
    List<Department> departmentList = ViewBag.AllDepartment;
    List<Course> courseList = ViewBag.AllCourses;
    
}

<head>
<style>
    label.error {
        color: red;
        font-weight: bold;
    }
</style>
    </head>

<fieldset style="width:50%">
    <legend>Course Assign to Teacher</legend>
    <form method="post" id="AsignCourse" name="AssignCourse">
        @if (ViewBag.Message != null)
            {
                <p>@ViewBag.Message</p>
            }

        <table>
            <tr>


                <td><label for="DepartmentIdsssss" />Department Name</td>
                <td>

                    <select id="DepartmentIdsssss" name="DepartmentId">
                        <option value="default">...Select...</option>
                    @foreach (var department in departmentList)
                    {
                        <option value="@department.DepartmentId">@department.DepartmentName</option>
                    }


                    </select>

                </td>




            </tr>
            <tr>
                <td><label for="TeacherId" />Teacher Name</td>
                <td>
                    <select id="TeacherId" name="TeacherId">

                        <option value="default">...Select...</option>
                    </select>
                </td>


            </tr>
            <tr>
                <td><label for="CreditToTake" />Credit To Take</td>
                <td><input type="text" id="CreditToTake" name="CreditToTake" /></td>

            </tr>
            <tr>
                <td><label for="RemainningCredit" />Remainning Credit</td>
                <td><input type="text" id="RemainningCredit" name="RemainningCredit" /></td>

            </tr>
            <tr>
                <td><label for="CourseCode" />CourseCode</td>
                <td>
                    <select id="CourseId" name="CourseId">
                        <option value="default">-------------Select--------------</option>

                    </select>
                </td>



            </tr>
            <tr>
                <td><label for="CourseName" />Course Name</td>
                <td>
                    <input type="text" id="CourseName" name="CourseName" />

                </td>

            </tr>
            <tr>
                <td><label for="CourseCredit" />Course Credit</td>
                <td>
                    <input type="text" id="CourseCredit" name="CourseCredit" />

                </td>


            </tr>
            <tr>
                <td></td>
                <td><input type="submit" name="hh" value="Assign Course" style="float:right"></td>
            </tr>

        </table>
    </form>
    @section scripts
    {
      
        <script src="~/Scripts/jquery-2.2.0.min.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script>
            $(document).ready(function() {
                $.validator.addMethod("valueNotEquals", function(value, element, arg) {
                    return arg != value;
                }, "Value must not equal arg.");

                $("#AsignCourse").validate({
                    rules: {
                        DepartmentId: {
                            valueNotEquals: "default"
                        },

                        TeacherId: {
                            valueNotEquals: "default"
                        },
                        CourseId: {
                            valueNotEquals: "default"
                        },
                        CreditToTake: {
                            required: true,
                        },
                        RemainningCredit: {
                            required: true
                        },
                        CourseName: {
                            required: true
                        },
                        CourseCredit: {
                            required: true
                        }
                    },
                    messages: {
                        CourseCredit: {
                            range: "Please Enter Value Between 0.5 and 5.0",
                            maxlength: "Pleasw Enter At Correct Formation"
                        },
                        DepartmentId: {
                            valueNotEquals: "Please select a Department"
                        },
                        TeacherId: {
                            valueNotEquals: "Please Select a Teacher"
                        },
                        CourseId: {
                            valueNotEquals: "Please Select a Course"
                        }
                        
                    }
                });


                $("#DepartmentIdsssss").change(function() {
                    $('#TeacherId').empty();
                    $('#CourseId').empty();
                    $('#CreditToTake').empty();
                    $('#RemainningCredit').empty();
                    $('#CourseName').empty();
                    $('#CourseCredit').empty();

                    var departmentId = $("#DepartmentIdsssss").val();
                    var remainCredit;
                    var selectedCourseCredit;
                    //alert(departmentId);
                    //("#departmentId").empty();
                    var json = { departmentId: departmentId };
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetTeachersByDepartmentId", "Teacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function(data) {
                            $("#TeacherId").append('<option value="">..Select..</option>');

                            $.each(data, function(key, value) {
                                //alert(key);

                                $("#TeacherId").append('<option value=' + value.TeacherId + '>' + value.TeacherName + '</option>');
                                //$("#CreditToTake").val(value.CreditToTake);


                            });


                            // ................
                            $("#TeacherId").change(function() {
                                $('#CreditToTake').empty();
                                $('#RemainningCredit').empty();
                                var credittotake;


                                $.each(data, function(key, value) {
                                    //credittotake = value.CreditToTake;

                                    $("#CreditToTake").val(value.CreditToTake);
                                    //alert(key);

                                    //$("#CreditToTake").val(value.CreditToTake);


                                });
                                /////////////...........................GetRemainningCredit
                                var teacherId = $("#TeacherId").val();
                                var json1 = { teacherId: teacherId };
                                $.ajax({
                                    type: "POST",
                                    url: '@Url.Action("GettRemainningCreditByTeacherId", "Teacher")',
                                    data: JSON.stringify({ cropName: teacherId }),
                                    dataType: 'text',
                                    contentType: "application/json; charset=utf-8",
                                    success: function (value) {
                                        credittotake = $("#CreditToTake").val();
                                        remainCredit = credittotake - value;
                                       
                                        $("#RemainningCredit").val(remainCredit);
                                        //alert(remainCredit);

                                    }
                                });

                                ///////////////


//alert(teacherId);


                            });

                            //............
                        }
                    });

                    //.....................For GetAllCourse By Department ID
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GettAllCourseByDepartmentId", "Teacher")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function(data) {
                            $("#CourseId").append('<option value="">...Select...</option>');

                            $.each(data, function(key, value) {
                                //alert(key);
                                $("#CourseId").append('<option value=' + value.CourseId + '>' + value.CourseCode + '</option>');
                                //$("#CreditToTake").val(value.CreditToTake);


                            });


                            // ................
                            $("#CourseId").change(function() {
                                $('#CourseName').empty();
                                $('#CourseCredit').empty();
                                var courseId = $("#CourseId").val();
                                var json3 = { courseId: courseId };
                                //alert(courseId);
                                $.ajax({
                                    type: "POST",
                                    url: '@Url.Action("GetAllCouseByCourseId", "Teacher")',
                                    contentType: "application/json; charset=utf-8",
                                    data: JSON.stringify(json3),
                                    success: function(data3) {
                                        $.each(data3, function (key, value) {
                                             $("#CourseName").val(value.CourseName);
                                            $("#CourseCredit").val(value.CourseCredit);
                                            selectedCourseCredit = value.CourseCredit;
                                            
                                            //alert(key);

                                            //$("#CreditToTake").val(value.CreditToTake);


                                        });
                                        //alert(selectedCourseCredit);
                                        //alert(remainCredit);

                                        var lastCredit = remainCredit - selectedCourseCredit;
                                        if (lastCredit <= 0) {
                                            alert("Teacher Credit Has been Fillup");
                                        }

                                    }
                                });


                                //alert(teacherId);
                                
                                


                            });

                            //............
                        }
                    });
                    //....................
                });
                //Code for Teacher id


            });
        </script>
    }



</fieldset>

UniversityManagement/Views/Teacher/SaveTeacher.cshtml
@using UniversityManagement.Models

@{
    Layout = null;
    List<Designation> aDesignationList = ViewBag.AllDesignation;
    List<Department> aDepartmentList = ViewBag.AllDepartment;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SaveTeacher</title>
    <style>
        label.error {
            color: red;
            font-weight: bold;
        }
    </style>

</head>
<body>
    <div>
        
        <fieldset style="width:50%">
            <legend>Save Course</legend>
            <form method="post" id="saveTeacher" name="saveTeacher">
                @if (ViewBag.Message != null)
                {
                    <p>@ViewBag.Message</p>
                }

                <table>
                    <tr>
                        <td><label for="TeacherName" />Teacher Name</td>
                        <td><input type="text" id="teacherName" name="TeacherName" /></td>
                    </tr>
                    <tr>
                        <td><label for="Address" />Address</td>
                        <td><input type="text" id="address" name="Address" /></td>

                    </tr>
                    <tr>
                        <td><label for="Email" />Email</td>
                        <td><input type="text" id="email" name="Email" /></td>

                    </tr>
                    <tr>
                        <td><label for="ContactNO" />Contact No</td>
                        <td><input type="text" id="contactNo" name="ContactNo" /></td>

                    </tr>
                    <tr>
                        <td><label for="Designation" />Deesignation</td>
                        <td>
                            <select id="designation" name="DesignationId">
                                <option value="default">-------------Select--------------</option>
                                @foreach (var DSG in aDesignationList)
                                {
                                    <option value="@DSG.DesignationId">@DSG.DesignationName</option>
                                }
                            </select>
                        </td>

                    </tr>
                    <tr>
                        <td><label for="DepartmentName" />Department Name</td>
                        <td>
                            <select id="departmentName" name="DepartmentId">
                                <option value="default">-------------Select--------------</option>
                                @foreach (var dept in aDepartmentList)
                                {
                                    <option value="@dept.DepartmentId">@dept.DepartmentName</option>
                                }
                            </select>
                        </td>

                    </tr>
                    <tr>
                        <td><label for="Credit" />Credit To Take</td>
                        <td><input type="text" id="creditToTake" name="CreditToTake" /></td>

                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" name="SaveTeacher" value="Save Teacher" style="float:right"></td>
                    </tr>
                </table>
            </form>
        </fieldset>  
    </div>
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            
            $.validator.addMethod("valueNotEquals", function (value, element, arg) {
                return arg != value;
            }, "Value must not equal arg.");

            $("#saveTeacher").validate({
                rules: {
                    TeacherName: {
                        required: true
                    },
                    Address: "required",
                    Email: {                        
                        required: true,
                        email: true
                    },
                    ContactNo: {
                        required: true,
                        maxlength: 11,
                        range: [0, 99999999999]

                    }, 
                    DesignationId: {                    
                        valueNotEquals: "default"
                    },
                    DepartmentId: {                    
                        valueNotEquals: "default"
                    },

                    CreditToTake: {
                        required: true,
                        range: [0, 10000],
                        maxlength: 3
                    }
                },
                messages: {
                    CourseCredit: {
                        range: "Please Enter Value Between 0.5 and 5.0"
                    },
                    DesignationId: {
                        valueNotEquals: "Please select a Designation"
                    },
                    DepartmentId: {                    
                        valueNotEquals: "Please select a Department"
                    },
                    ContactNo: {
                        range: "Please Enter Correct Phone Format"

                    },
                    CreditToTake: {                   
                        range: "Please Enter A Positive Number"

        }
                

            }
        });

    });
    </script>

</body>
</html>

UniversityManagement/Views/Teacher/TestAssignCourse.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestAssignCourse</title>
</head>
<body>
    <div>
        
        <form id="hh" name="hh" method="post">
            @if (ViewBag.Message != null)
            {
                <p>@ViewBag.Message</p>
            }
            <table>
                <tr>


                    <td><label for="DepartmentIdsssss" />Department Name</td>
                    <td>

                        <select id="DepartmentIdsssss" name="DepartmentId">
                            @*<option value="">...Select...</option>
            @foreach (var department in departmentList)
            {
                <option value="@department.DepartmentId">@department.DepartmentName</option>
            }*@


                        </select>

                    </td>




                </tr>
                <tr>
                    <td><label for="TeacherId" />Teacher Name</td>
                    <td>
                        <select id="TeacherId" name="TeacherId">

                            <option value="">...Select...</option>
                        </select>
                    </td>


                </tr>
                <tr>
                    <td><label for="CreditToTake" />Credit To Take</td>
                    <td><input type="text" id="CreditToTake" name="CreditToTake" /></td>

                </tr>
                <tr>
                    <td><label for="RemainningCredit" />Remainning Credit</td>
                    <td><input type="text" id="RemainningCredit" name="RemainningCredit" /></td>

                </tr>
                <tr>
                    <td><label for="CourseCode" />CourseCode</td>
                    <td>
                        <select id="CourseId" name="CourseId">
                            <option>-------------Select--------------</option>

                        </select>
                    </td>



                </tr>
                <tr>
                    <td><label for="CourseName" />Course Name</td>
                    <td>
                        <input type="text" id="CourseName" name="CourseName" />

                    </td>

                </tr>
                <tr>
                    <td><label for="CourseCredit" />Course Credit</td>
                    <td>
                        <input type="text" id="CourseCredit" name="CourseCredit" />

                    </td>


                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" name="hh" value="hh" style="float:right"></td>
                </tr>
            </table>
        </form>

    </div>
</body>
</html>

UniversityManagement/Views/Teacher/UnAssignCourses.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>UnAssignCourses</title>
</head>
<body>
    <div>
        <fieldset style="width:50%">
            <legend>.Unassign All Courses</legend>
            <form method="post" id="AsignCourse">
                @if (ViewBag.Message != null)
                {
                    <p>@ViewBag.Message</p>
                }

              
                <input type="submit" name="unassigned" value="Unassign Courses" style="text-align: center">
                    
            </form>
        </fieldset>   
    </div>
</body>
</html>